// Architecture diagrams, drawn only from the resume bullets for each project.
// Each has a wide layout (≥1200px) and a narrow one; coordinates are SVG units.

export type DiagramNode = {
  id: string;
  label: string[];
  sub?: string[];
  x: number;
  y: number;
  w?: number;
  h?: number;
};

export type Direction = "right" | "left" | "up" | "down";

export type DiagramEdge = {
  id: string;
  d: string;
  end: [number, number];
  dir: Direction;
};

// A dashed outline around nodes that share one origin, with a caption above it.
export type DiagramGroup = {
  id: string;
  label: string;
  x: number;
  y: number;
  w: number;
  h: number;
};

export type DiagramLayout = {
  width: number;
  height: number;
  nodes: DiagramNode[];
  edges: DiagramEdge[];
  groups?: DiagramGroup[];
};

export type Diagram = { title: string; wide: DiagramLayout; narrow: DiagramLayout };

export const NODE_W = 168;
export const NODE_H = 72;

// Resume: LLMs "generate script, animation code and audio"; the animations are
// rendered in headless Chromium and FFmpeg merges audio and video. Nothing more
// specific (e.g. which model makes which output) is drawn.
export const shiksha: Diagram = {
  title:
    "Shiksha pipeline: a text prompt goes to LLMs (GPT-4o and Gemini 1.5), which generate a script, animation code and audio. Headless Chromium (Pyppeteer) renders the animation code; FFmpeg merges the render with the audio into a narrated video.",
  wide: {
    width: 1200,
    height: 424,
    groups: [{ id: "outputs", label: "generated by the LLMs", x: 400, y: 32, w: 192, h: 384 }],
    nodes: [
      { id: "prompt", label: ["Text prompt"], sub: ["React + Flask app"], x: 0, y: 188 },
      { id: "llms", label: ["LLMs"], sub: ["GPT-4o · Gemini 1.5"], x: 206, y: 188 },
      { id: "script", label: ["Script"], x: 412, y: 44 },
      { id: "anim", label: ["Animation code"], x: 412, y: 188 },
      { id: "audio", label: ["Audio"], sub: ["voiceover"], x: 412, y: 332 },
      { id: "chromium", label: ["Headless Chromium"], sub: ["Pyppeteer"], x: 618, y: 188 },
      { id: "ffmpeg", label: ["FFmpeg"], sub: ["merges audio + video"], x: 824, y: 188 },
      { id: "video", label: ["Narrated video"], sub: ["synced voiceover"], x: 1030, y: 188 },
    ],
    edges: [
      { id: "prompt-llms", d: "M168 224 H206", end: [206, 224], dir: "right" },
      { id: "llms-outputs", d: "M374 224 H400", end: [400, 224], dir: "right" },
      { id: "anim-chromium", d: "M580 224 H618", end: [618, 224], dir: "right" },
      { id: "chromium-ffmpeg", d: "M786 224 H824", end: [824, 224], dir: "right" },
      { id: "audio-ffmpeg", d: "M580 368 H892 Q908 368 908 352 V260", end: [908, 260], dir: "up" },
      { id: "ffmpeg-video", d: "M992 224 H1030", end: [1030, 224], dir: "right" },
    ],
  },
  narrow: {
    width: 360,
    height: 696,
    groups: [{ id: "outputs", label: "generated by the LLMs", x: 0, y: 228, w: 360, h: 96 }],
    nodes: [
      { id: "prompt", label: ["Text prompt"], sub: ["React + Flask app"], x: 96, y: 0 },
      { id: "llms", label: ["LLMs"], sub: ["GPT-4o · Gemini 1.5"], x: 96, y: 112 },
      { id: "script", label: ["Script"], x: 12, y: 240, w: 104 },
      { id: "anim", label: ["Animation", "code"], x: 128, y: 240, w: 104 },
      { id: "audio", label: ["Audio"], sub: ["voiceover"], x: 244, y: 240, w: 104 },
      { id: "chromium", label: ["Headless Chromium"], sub: ["Pyppeteer"], x: 96, y: 368 },
      { id: "ffmpeg", label: ["FFmpeg"], sub: ["merges audio + video"], x: 96, y: 496 },
      { id: "video", label: ["Narrated video"], sub: ["synced voiceover"], x: 96, y: 624 },
    ],
    edges: [
      { id: "prompt-llms", d: "M180 72 V112", end: [180, 112], dir: "down" },
      { id: "llms-outputs", d: "M180 184 V228", end: [180, 228], dir: "down" },
      { id: "anim-chromium", d: "M180 312 V368", end: [180, 368], dir: "down" },
      { id: "chromium-ffmpeg", d: "M180 440 V496", end: [180, 496], dir: "down" },
      { id: "audio-ffmpeg", d: "M296 312 V516 Q296 532 280 532 H264", end: [264, 532], dir: "left" },
      { id: "ffmpeg-video", d: "M180 568 V624", end: [180, 624], dir: "down" },
    ],
  },
};

export const shikshaStages = [
  {
    label: "Prompt",
    nodes: ["prompt"],
    edges: [],
    groups: [],
    text: "A text prompt comes in through the React front end and reaches the Flask back end.",
  },
  {
    label: "Generate",
    nodes: ["llms", "script", "anim", "audio"],
    edges: ["prompt-llms", "llms-outputs"],
    groups: ["outputs"],
    text: "Multiple LLMs (GPT-4o and Gemini 1.5, with Groq for low-latency inference) generate three things: the script, the animation code and the audio.",
  },
  {
    label: "Render",
    nodes: ["chromium"],
    edges: ["anim-chromium"],
    groups: [],
    text: "Headless Chromium, driven by Pyppeteer, renders the generated animation code. The models write code; a browser turns it into animation.",
  },
  {
    label: "Merge",
    nodes: ["ffmpeg"],
    edges: ["chromium-ffmpeg", "audio-ffmpeg"],
    groups: [],
    text: "FFmpeg merges the rendered animation with the audio, so the voiceover stays in sync with the picture.",
  },
  {
    label: "Deliver",
    nodes: ["video"],
    edges: ["ffmpeg-video"],
    groups: [],
    text: "Out comes a narrated, animated educational video, served back through the app. I built and deployed the whole pipeline solo.",
  },
] as const;

export const voicedesk: Diagram = {
  title:
    "VoiceDesk: live audio from a Streamlit UI goes to Whisper for speech-to-text, then to a ReAct agent (LangChain, LLaMA 3.3) that retrieves from a ChromaDB knowledge base of 16 documents embedded with sentence-transformers, and replies by voice with a transcript.",
  wide: {
    width: 900,
    height: 296,
    nodes: [
      { id: "audio", label: ["Live audio"], sub: ["Streamlit UI"], x: 0, y: 20, h: 80 },
      { id: "whisper", label: ["Whisper"], sub: ["speech-to-text"], x: 244, y: 20, h: 80 },
      { id: "agent", label: ["ReAct agent"], sub: ["LangChain", "LLaMA 3.3"], x: 488, y: 20, h: 80 },
      {
        id: "retrieval",
        label: ["RAG retrieval"],
        sub: ["ChromaDB", "sentence-transformers", "16-document corpus"],
        x: 488,
        y: 176,
        w: 184,
        h: 96,
      },
      { id: "reply", label: ["Reply"], sub: ["voice + transcript"], x: 732, y: 20, h: 80 },
    ],
    edges: [
      { id: "audio-whisper", d: "M168 60 H244", end: [244, 60], dir: "right" },
      { id: "whisper-agent", d: "M412 60 H488", end: [488, 60], dir: "right" },
      { id: "agent-retrieval", d: "M548 100 V176", end: [548, 176], dir: "down" },
      { id: "retrieval-agent", d: "M596 176 V100", end: [596, 100], dir: "up" },
      { id: "agent-reply", d: "M656 60 H732", end: [732, 60], dir: "right" },
    ],
  },
  narrow: {
    width: 384,
    height: 448,
    nodes: [
      { id: "audio", label: ["Live audio"], sub: ["Streamlit UI"], x: 96, y: 0 },
      { id: "whisper", label: ["Whisper"], sub: ["speech-to-text"], x: 96, y: 112 },
      { id: "agent", label: ["ReAct agent"], sub: ["LangChain", "LLaMA 3.3"], x: 0, y: 236, h: 80 },
      {
        id: "retrieval",
        label: ["RAG retrieval"],
        sub: ["ChromaDB", "sentence-transformers", "16-document corpus"],
        x: 192,
        y: 232,
        w: 192,
        h: 96,
      },
      { id: "reply", label: ["Reply"], sub: ["voice + transcript"], x: 0, y: 376 },
    ],
    edges: [
      { id: "audio-whisper", d: "M180 72 V112", end: [180, 112], dir: "down" },
      { id: "whisper-agent", d: "M180 184 V204 Q180 212 172 212 H92 Q84 212 84 220 V236", end: [84, 236], dir: "down" },
      { id: "agent-retrieval", d: "M168 262 H192", end: [192, 262], dir: "right" },
      { id: "retrieval-agent", d: "M192 298 H168", end: [168, 298], dir: "left" },
      { id: "agent-reply", d: "M84 316 V376", end: [84, 376], dir: "down" },
    ],
  },
};

export const veridex: Diagram = {
  title:
    "Veridex: frame-level video data goes through a ResNet-50 backbone (transfer learning) and a custom dropout head to a binary real-or-fake prediction.",
  wide: {
    width: 900,
    height: 120,
    nodes: [
      { id: "frames", label: ["Video frames"], sub: ["frame-level data"], x: 0, y: 24 },
      { id: "backbone", label: ["ResNet-50"], sub: ["transfer learning"], x: 244, y: 24 },
      { id: "head", label: ["Dropout head"], sub: ["custom"], x: 488, y: 24 },
      { id: "output", label: ["Real / fake"], sub: ["binary"], x: 732, y: 24 },
    ],
    edges: [
      { id: "frames-backbone", d: "M168 60 H244", end: [244, 60], dir: "right" },
      { id: "backbone-head", d: "M412 60 H488", end: [488, 60], dir: "right" },
      { id: "head-output", d: "M656 60 H732", end: [732, 60], dir: "right" },
    ],
  },
  narrow: {
    width: 360,
    height: 408,
    nodes: [
      { id: "frames", label: ["Video frames"], sub: ["frame-level data"], x: 96, y: 0 },
      { id: "backbone", label: ["ResNet-50"], sub: ["transfer learning"], x: 96, y: 112 },
      { id: "head", label: ["Dropout head"], sub: ["custom"], x: 96, y: 224 },
      { id: "output", label: ["Real / fake"], sub: ["binary"], x: 96, y: 336 },
    ],
    edges: [
      { id: "frames-backbone", d: "M180 72 V112", end: [180, 112], dir: "down" },
      { id: "backbone-head", d: "M180 184 V224", end: [180, 224], dir: "down" },
      { id: "head-output", d: "M180 296 V336", end: [180, 336], dir: "down" },
    ],
  },
};

export const diagrams = { shiksha, voicedesk, veridex } as const;
